---
title: "Radicalization Lab"
subtitle: "Code sheet 1: Data preparation"
author: "Arda Ergin"
output:
  rmdformats::downcute:
    downcute_theme: "chaos"
---

# Setup
IMPORTANT FOR THE USER OF THIS SCRIPT: you have to load the R package "**RadLab**". This is necessary for the code to work properly. See [the GitHub repository](https://github.com/ardaergin/RadLab) for further information.           

The code below loads the RadLab package, you need to download the "devtools" package first, you can do so with install.packages("devtools").
```{r, message=FALSE, warning=FALSE}
# First install the package with: 

devtools::install_github("ardaergin/RadLab")
library(RadLab)
library(dplyr)
```

```{r}
load("data_working/d_combined.Rdata")

df_ilr <- RadLab::prepare_compositional_data(data_combined)

colnames(df_ilr)

df_ilr_x <- df_ilr %>% select(time, 
                  ID, 
                  Experiment, 
                  excluded, injustice, personal, violence,
                  ilr1, ilr2, ilr3)

write.csv(df_ilr_x, file = "data_working/ilr_transformed_full_data.csv", row.names = FALSE)
```


```{r}
install.packages("dtwclust")


install.packages("depmixS4")
library(depmixS4)

# Define the HMM model with 3 hidden states (you can adjust as needed)
model <- depmix(list(ina ~ 1, na ~ 1, nna ~ 1, enna ~ 1), 
                data = responses, nstates = 3, family = gaussian())

# Fit the model
fit <- fit(model)

# Extract posterior state probabilities
post_probs <- posterior(fit)

# Assign clusters based on the dominant state
clusters <- apply(post_probs, 1, which.max)

```



