---
title: "Radicalization Lab"
subtitle: "Code sheet 3: ILR Analysis"
author: "Arda Ergin"
output:
  rmdformats::downcute:
    downcute_theme: "chaos"
---

# Setup
IMPORTANT FOR THE USER OF THIS SCRIPT: you have to load the R package "**RadLab**". This is necessary for the code to work properly. See [the GitHub repository](https://github.com/ardaergin/RadLab) for further information.           

The code below loads the RadLab package, you need to download the "devtools" package first, you can do so with install.packages("devtools").
```{r, message=FALSE, warning=FALSE}
# devtools::install_github("ardaergin/RadLab")
# library(RadLab)
devtools::load_all(".")
library(dplyr)
library(tidyr)
library(ggplot2)
library(stats)
library(lme4)
library(lmerTest)
library(compositions)
library(zCompositions)
```


```{r}
load("../data/data_working/d_study1.Rdata")
load("../data/data_working/d_study2.Rdata")
load("../data/data_working/d_study3.Rdata")
load("../data/data_working/d_study4.Rdata")
load("../data/data_working/d_study5.Rdata")
load("../data/data_working/d_study6.Rdata")
load("../data/data_working/d_study7.Rdata")
load("../data/data_working/d_study8.Rdata")
```


```{r}
# List of datasets and their names
datasets <- list(
  d_study1 = d_study1, 
  d_study2 = d_study2, 
  d_study3 = d_study3, 
  d_study4 = d_study4, 
  d_study5 = d_study5, 
  d_study6 = d_study6, 
  d_study7 = d_study7, 
  d_study8 = d_study8
)
datasets_transformed <- list()

# Initialize a counter for unique condition numbers
condition_counter <- 0

# Loop through each dataset
for (name in names(datasets)) {
  dataset <- datasets[[name]]  # Access the dataset by name

  # Transform dataset
  ilr_transformed_dataset <- RadLab::prepare_compositional_data(dataset)

  # Map conditions to unique numeric values
  unique_conditions <- unique(ilr_transformed_dataset$condition_f)
  condition_map <- setNames(
    seq(condition_counter + 1, condition_counter + length(unique_conditions)), 
    unique_conditions
  )
  condition_counter <- condition_counter + length(unique_conditions)

  # Convert `condition_f` to numeric using the mapping
  ilr_transformed_dataset <- ilr_transformed_dataset %>%
    dplyr::mutate(
      gender = as.numeric(gender_f),
      condition = as.numeric(as.character(condition_map[as.character(condition_f)]))
    )

  # Select columns
  ilr_transformed_dataset <- ilr_transformed_dataset %>%
    dplyr::select(
      time, ID, 
      ina, na, nna, enna,
      ilr1, ilr2, ilr3, 
      excluded, injustice, personal, violence,
      Vignette,
      gender, age,
      condition,
      Experiment
    )
  datasets_transformed <- append(datasets_transformed, list(ilr_transformed_dataset))

  # Wide transformation
  wide_data <- ilr_transformed_dataset %>%
    pivot_wider(
      names_from = time,
      values_from = c(ilr1, ilr2, ilr3, excluded, injustice, personal, violence, Vignette)
    )

  # File names for saving transformed data
  file_name_csv_long <- paste0("../data/data_ilr_transformed/", name, "_long", ".csv")
  file_name_rdata_long <- paste0("../data/data_ilr_transformed/", name, "_long", ".Rdata")
  file_name_csv_wide <- paste0("../data/data_ilr_transformed/", name, "_wide", ".csv")
  file_name_rdata_wide <- paste0("../data/data_ilr_transformed/", name, "_wide", ".Rdata")

  # Write transformed data (long format) to a CSV file
  write.csv(ilr_transformed_dataset, file_name_csv_long, row.names = FALSE)
  save(ilr_transformed_dataset, file = file_name_rdata_long)

  # Write transformed data (wide format) to a CSV file
  write.csv(wide_data, file_name_csv_wide, row.names = FALSE)
  save(wide_data, file = file_name_rdata_wide)
}
```

```{r}
df <- rbind(datasets_transformed[[1]], datasets_transformed[[2]], 
            datasets_transformed[[3]], datasets_transformed[[4]],
            datasets_transformed[[5]], datasets_transformed[[6]], 
            datasets_transformed[[7]], datasets_transformed[[8]])
```

With time:
```{r}
ilr1_model <- lmerTest::lmer(
  ilr1 ~ excluded*time + injustice*time + personal*time + violence*time +
    (1 | Experiment/condition),
  data = df,
  control = lmerControl(optimizer = "bobyqa")
)
df$ilr1_residual <- resid(ilr1_model)

ilr2_model <- lmerTest::lmer(
  ilr2 ~ excluded*time + injustice*time + personal*time + violence*time +
    (1 | Experiment/condition),
  data = df,
  control = lmerControl(optimizer = "bobyqa")
)
df$ilr2_residual <- resid(ilr2_model)

ilr3_model <- lmerTest::lmer(
  ilr3 ~ excluded*time + injustice*time + personal*time + violence*time +
    (1 | Experiment/condition),
  data = df,
  control = lmerControl(optimizer = "bobyqa")
)
df$ilr3_residual <- resid(ilr3_model)
```

```{r}
write.csv(df, "../data/data_ilr_transformed/combined_data__resid_with_time.csv", row.names = FALSE)
```

Without time
```{r}
ilr1_model <- lmerTest::lmer(
  ilr1 ~ excluded + injustice + personal + violence +
    (1 | Experiment/condition),
  data = df,
  control = lmerControl(optimizer = "bobyqa")
)
df$ilr1_residual <- resid(ilr1_model)

ilr2_model <- lmerTest::lmer(
  ilr2 ~ excluded + injustice + personal + violence +
    (1 | Experiment/condition),
  data = df,
  control = lmerControl(optimizer = "bobyqa")
)
df$ilr2_residual <- resid(ilr2_model)

ilr3_model <- lmerTest::lmer(
  ilr3 ~ excluded + injustice + personal + violence +
    (1 | Experiment/condition),
  data = df,
  control = lmerControl(optimizer = "bobyqa")
)
df$ilr3_residual <- resid(ilr3_model)
```

```{r}
write.csv(df, "../data/data_ilr_transformed/combined_data__resid_without_time.csv", row.names = FALSE)
```





```{r}
# For d_study1
data <- d_study1
ilr_data <- RadLab::prepare_compositional_data(data)

ilr1_model_1 <- lmerTest::lmer(
  ilr1 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr1_model_1)

ilr2_model_1 <- lmerTest::lmer(
  ilr2 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr2_model_1)

ilr3_model_1 <- lmerTest::lmer(
  ilr3 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr3_model_1)

# For d_study2
data <- d_study2
ilr_data <- RadLab::prepare_compositional_data(data)

ilr1_model_2 <- lmerTest::lmer(
  ilr1 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr1_model_2)

ilr2_model_2 <- lmerTest::lmer(
  ilr2 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr2_model_2)

ilr3_model_2 <- lmerTest::lmer(
  ilr3 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr3_model_2)

# For d_study3
data <- d_study3
ilr_data <- RadLab::prepare_compositional_data(data)

ilr1_model_3 <- lmerTest::lmer(
  ilr1 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr1_model_3)

ilr2_model_3 <- lmerTest::lmer(
  ilr2 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr2_model_3)

ilr3_model_3 <- lmerTest::lmer(
  ilr3 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr3_model_3)

# For d_study4
data <- d_study4
ilr_data <- RadLab::prepare_compositional_data(data)

ilr1_model_4 <- lmerTest::lmer(
  ilr1 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr1_model_4)

ilr2_model_4 <- lmerTest::lmer(
  ilr2 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr2_model_4)

ilr3_model_4 <- lmerTest::lmer(
  ilr3 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr3_model_4)

# For d_study5
data <- d_study5
ilr_data <- RadLab::prepare_compositional_data(data)

ilr1_model_5 <- lmerTest::lmer(
  ilr1 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr1_model_5)

ilr2_model_5 <- lmerTest::lmer(
  ilr2 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr2_model_5)

ilr3_model_5 <- lmerTest::lmer(
  ilr3 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr3_model_5)

# For d_study6
data <- d_study6
ilr_data <- RadLab::prepare_compositional_data(data)

ilr1_model_6 <- lmerTest::lmer(
  ilr1 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr1_model_6)

ilr2_model_6 <- lmerTest::lmer(
  ilr2 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr2_model_6)

ilr3_model_6 <- lmerTest::lmer(
  ilr3 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr3_model_6)

# For d_study7
data <- d_study7
ilr_data <- RadLab::prepare_compositional_data(data)

ilr1_model_7 <- lmerTest::lmer(
  ilr1 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr1_model_7)

ilr2_model_7 <- lmerTest::lmer(
  ilr2 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr2_model_7)

ilr3_model_7 <- lmerTest::lmer(
  ilr3 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr3_model_7)

# For d_study8
data <- d_study8
ilr_data <- RadLab::prepare_compositional_data(data)

ilr1_model_8 <- lmerTest::lmer(
  ilr1 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr1_model_8)

ilr2_model_8 <- lmerTest::lmer(
  ilr2 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr2_model_8)

ilr3_model_8 <- lmerTest::lmer(
  ilr3 ~ time + excluded + injustice + personal + violence +
    (1 + time | ID),
  data = ilr_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(ilr3_model_8)
```


```{r}
load('../models/mcmc_results.Rdata')

summary(mcmc_model)

library(MCMCglmm)

summary(mcmc_model)
```



