#' Comprehensive Vignette Action Analysis Visualization
#'
#' @description
#' Generates a suite of three visualizations to analyze vignette responses:
#' 1. **Ribbon Plot:** Overlapping lines with shaded error ribbons (silhouettes).
#' 2. **Faceted Plot:** A 2x2 grid separating action types to see individual variation clearly.
#' 3. **Bar Plot:** Discrete comparison of means for each vignette with error bars.
#'
#' @details
#' All plots are clamped between 0 and 100 to ensure error bars do not represent
#' impossible values on a fixed percentage scale.
#'
#' @param data_long A long-format data frame generated by `wide_to_long`.
#' Must contain `time`, `Vignette`, `ina`, `na`, `nna`, and `enna`.
#' @param error_type Character. Use `"se"` for Standard Error (precision of the mean)
#' or `"sd"` for Standard Deviation (spread of individual responses). Defaults to `"se"`.
#'
#' @return A named list of three `ggplot2` objects: `ribbon`, `faceted`, and `bars`.
#' @export
#'
#' @examples
#' # vignette_viz <- plot_vignette_analysis(d_study1_long, error_type = "sd")
#' # vignette_viz$ribbon
#' # vignette_viz$faceted
#' # vignette_viz$bars

plot_vignette_analysis <- function(data_long, error_type = "se") {

  # --- 1. Data Preparation ---
  summary_df <- data_long %>%
    tidyr::pivot_longer(
      cols = c(ina, na, nna, enna),
      names_to = "action_type",
      values_to = "score"
    ) %>%
    dplyr::mutate(action_type = factor(action_type,
                                       levels = c("ina", "na", "nna", "enna"),
                                       labels = c("Inaction", "Normative",
                                                  "Non-Normative", "Extreme Non-Normative"))) %>%
    dplyr::group_by(Vignette, action_type, time) %>%
    dplyr::summarise(
      mean_score = mean(score, na.rm = TRUE),
      sd_score = sd(score, na.rm = TRUE),
      n = dplyr::n(),
      .groups = "drop"
    ) %>%
    dplyr::mutate(
      val_error = if(error_type == "se") sd_score/sqrt(n) else sd_score,
      # Clamping bounds to 0-100
      lower = pmax(0, mean_score - val_error),
      upper = pmin(100, mean_score + val_error)
    )

  # --- Common Theme Elements ---
  common_theme <- list(
    ggplot2::theme_classic(),
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)),
    ggplot2::scale_x_continuous(breaks = unique(summary_df$time),
                                labels = unique(summary_df$Vignette)),
    ggplot2::scale_y_continuous(limits = c(0, 100)),
    ggplot2::labs(y = "Mean Score (0-100)", x = "Vignette",
                  color = "Action Type", fill = "Action Type")
  )

  # --- 2. Plot A: Overlapping Ribbons ---
  p_ribbon <- ggplot2::ggplot(summary_df, ggplot2::aes(x = time, y = mean_score,
                                                       color = action_type, fill = action_type)) +
    ggplot2::geom_ribbon(ggplot2::aes(ymin = lower, ymax = upper), alpha = 0.15, color = NA) +
    ggplot2::geom_line(linewidth = 1) +
    ggplot2::geom_point() +
    common_theme +
    ggplot2::ggtitle(paste("Mean Action Profiles (", error_type, ")"))

  # --- 3. Plot B: Faceted Ribbons (2x2 Grid) ---
  p_faceted <- p_ribbon +
    ggplot2::facet_wrap(~action_type, ncol = 2) +
    ggplot2::theme_bw() +
    ggplot2::theme(legend.position = "none",
                   axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, size = 7)) +
    ggplot2::scale_y_continuous(limits = c(0, 100)) +
    ggplot2::ggtitle(paste("Individual Action Variation (", error_type, ")"))

  # --- 4. Plot C: Bars with Error Bars ---
  p_bars <- ggplot2::ggplot(summary_df, ggplot2::aes(x = factor(time), y = mean_score,
                                                     fill = action_type)) +
    ggplot2::geom_bar(stat = "identity", position = ggplot2::position_dodge(width = 0.8), width = 0.7) +
    ggplot2::geom_errorbar(ggplot2::aes(ymin = lower, ymax = upper),
                           position = ggplot2::position_dodge(width = 0.8), width = 0.25) +
    ggplot2::theme_classic() +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)) +
    ggplot2::scale_x_discrete(labels = unique(summary_df$Vignette)) +
    ggplot2::scale_y_continuous(limits = c(0, 100)) +
    ggplot2::labs(y = "Mean Score", x = "Vignette", fill = "Action Type") +
    ggplot2::ggtitle(paste("Vignette Comparison (", error_type, ")"))

  return(list(ribbon = p_ribbon, faceted = p_faceted, bars = p_bars))
}
